apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: test-store
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: test-store
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: test-store
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-store
      tier: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
        - image: ybonjour/test-store-backend
          name: backend
          env:
            - name: CASSANDRA_HOST
              value: "cassandra"
            - name: CASSANDRA_PORT
              value: "9042"
          ports:
            - containerPort: 8080
              name: backend